item {
    id: 1
    name: ‘airplane’
}
item {
    id: 2
    name: 'automobile'
}
item {
    id: 3
    name: 'bird'
}
item {
    id: 4
    name: 'cat'
}
item {
    id: 5
    name: 'deer'
}
item {
    id: 6
    name: 'dog'
}
item {
    id: 7
    name: 'frog'
}
item {
    id: 8
    name: 'horse'
}
item {
    id: 9
    name: 'ship'
}
item {
    id: 10
    name: 'truck'
}